//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificCentreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorComment
    {
        public int CommentId { get; set; }
        public int ProjectId { get; set; }
        public System.Guid AuthorId { get; set; }
        public int ReviewId { get; set; }
        public System.DateTime CommentedOnDate { get; set; }
        public bool Approved { get; set; }
        public string CommentContent { get; set; }
    
        public virtual ScientificCentreUser ScientificCentreUser { get; set; }
        public virtual ScientificProject ScientificProject { get; set; }
        public virtual ProjectReview ProjectReview { get; set; }
    }
}
