//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificCentreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CamundaUserProcess
    {
        public System.Guid ProcessInstanceId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.Guid> TaskId { get; set; }
        public string TaskName { get; set; }
        public string ProcesName { get; set; }
        public string WorkerName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual ScientificCentreUser ScientificCentreUser { get; set; }
    }
}
