//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificCentreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MagazineWorker
    {
        public int MagazineId { get; set; }
        public System.Guid ReviewerEditorId { get; set; }
        public string Role { get; set; }
        public Nullable<int> AreaId { get; set; }
    
        public virtual Magazine Magazine { get; set; }
        public virtual ScientificCentreUser ScientificCentreUser { get; set; }
        public virtual ScientificArea ScientificArea { get; set; }
    }
}
