//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificCentreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public System.Guid UserId { get; set; }
        public byte PaymentType { get; set; }
        public int PaymentSum { get; set; }
        public byte SubibscriptionPackageOrProduct { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string Note { get; set; }
        public bool Successfull { get; set; }
    
        public virtual ScientificCentreUser ScientificCentreUser { get; set; }
    }
}
