//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificCentreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectReview
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectReview()
        {
            this.AuthorComments = new HashSet<AuthorComment>();
        }
    
        public int ReviewId { get; set; }
        public int ProjectId { get; set; }
        public System.Guid ReviewerId { get; set; }
        public System.DateTime ReviewedOnDate { get; set; }
        public bool Approved { get; set; }
        public Nullable<bool> OnlyForEditor { get; set; }
        public int AreaId { get; set; }
        public int Rating { get; set; }
        public string ReviewContent { get; set; }
        public string EditorContent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthorComment> AuthorComments { get; set; }
        public virtual ScientificArea ScientificArea { get; set; }
        public virtual ScientificProject ScientificProject { get; set; }
        public virtual ScientificCentreUser ScientificCentreUser { get; set; }
    }
}
