//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificCentreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectsEditor
    {
        public int Id { get; set; }
        public System.Guid EditorId { get; set; }
        public int ProjectId { get; set; }
    
        public virtual ScientificCentreUser ScientificCentreUser { get; set; }
        public virtual ScientificProject ScientificProject { get; set; }
    }
}
