//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificCentreData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScientificCentreEntities : DbContext
    {
        public ScientificCentreEntities()
            : base("name=ScientificCentreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Magazine> Magazines { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<ProjectAuthor> ProjectAuthors { get; set; }
        public virtual DbSet<ScientificArea> ScientificAreas { get; set; }
        public virtual DbSet<ScientificCentreUser> ScientificCentreUsers { get; set; }
        public virtual DbSet<Subscription> Subscriptions { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<Town> Towns { get; set; }
        public virtual DbSet<UserInventory> UserInventories { get; set; }
        public virtual DbSet<ScientificProject> ScientificProjects { get; set; }
        public virtual DbSet<MagazineWorker> MagazineWorkers { get; set; }
        public virtual DbSet<AuthorComment> AuthorComments { get; set; }
        public virtual DbSet<ProjectReview> ProjectReviews { get; set; }
        public virtual DbSet<ProjectsEditor> ProjectsEditors { get; set; }
        public virtual DbSet<CamundaUserProcess> CamundaUserProcesses { get; set; }
    }
}
