//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificCentreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScientificProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScientificProject()
        {
            this.ProjectAuthors = new HashSet<ProjectAuthor>();
            this.Tasks = new HashSet<Task>();
            this.Magazines = new HashSet<Magazine>();
            this.AuthorComments = new HashSet<AuthorComment>();
            this.ProjectReviews = new HashSet<ProjectReview>();
            this.ProjectsEditors = new HashSet<ProjectsEditor>();
        }
    
        public int ProjectId { get; set; }
        public string Subject { get; set; }
        public string KeyWords { get; set; }
        public string Abstract { get; set; }
        public int ScientificAreaId { get; set; }
        public string NotRegisteredAutorsInfo { get; set; }
        public string ProjectContent { get; set; }
        public System.DateTime SentOnDate { get; set; }
        public Nullable<System.DateTime> LastDateTimeEdited { get; set; }
        public bool Accepted { get; set; }
        public bool Removed { get; set; }
        public string FileName { get; set; }
        public string Comment { get; set; }
        public string DOI { get; set; }
        public string PdfHtmlFileName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectAuthor> ProjectAuthors { get; set; }
        public virtual ScientificArea ScientificArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Magazine> Magazines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuthorComment> AuthorComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectReview> ProjectReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectsEditor> ProjectsEditors { get; set; }
    }
}
