//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificCentreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.ScientificCentreUsers = new HashSet<ScientificCentreUser>();
        }
    
        public int TaskId { get; set; }
        public int ProjectId { get; set; }
        public string TaskDescription { get; set; }
        public System.DateTime StartedOnDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public bool Processed { get; set; }
        public bool Expired { get; set; }
        public byte TaskType { get; set; }
        public Nullable<bool> OutcomeResult { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScientificCentreUser> ScientificCentreUsers { get; set; }
        public virtual ScientificProject ScientificProject { get; set; }
    }
}
