//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScientificCentreData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInventory
    {
        public int InventoryId { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<byte> ProjectId { get; set; }
        public Nullable<int> MagazineId { get; set; }
        public System.DateTime DateAcquired { get; set; }
    
        public virtual Magazine Magazine { get; set; }
        public virtual ScientificCentreUser ScientificCentreUser { get; set; }
    }
}
